### ISSUE TITLE
Doesn't seem to be working.. multiple Stickies windows open and Rosetta just for a workflow?

### ISSUE THREAD

**Issue by paulmoons** [Yiiipu/ChatGPT-for-Alfred#1]
Entered all the details required into the .py file but this seems to be a little under cooked. I couldn't get it to work at all.. Also, the ChatID only appears in the URL on previous chats. Not sure if that is the issue but yeah.. didn't work for me at all. :(

**Comment by paulmoons** [comment]
Wrong forum.

**Comment by Yiiipu** [comment]
1. It is used to open the previous created chat so that you can continue different conversations for different tasks at any time. For example, you can duplicate this workflow and set one's keyword as "travel planner" and the other's as "weekly plan". Every time you use "travel planner", you do not need to tell the bot again where you are traveling now. You can just type "travel planner I get one more free night, where should I visit".
2. can you tell me what is the exact problem you encounter? thanks!

**Comment by paulmoons** [comment]
I've jumped to a different solution that uses a small app in the menu bar. Basically this would just open a blank note and if I asked ChatGPT anything, another blank note would appear.
